name: mariadb
type: db
title: MariaDB
hostname: mariadb
containers:
- name: mariadb
  ports:
  - name: mariadb
    number: 3365
  env:
  - name: MYSQL_ROOT_PASSWORD
    value: '{{root_password}}'
  volumes:
  - path: /var/lib/mysql
    name: data
options:
- version: 10.3
  stability_tag: 1.2.3
scalable: false
labels:
- mariadb
- mysql
tokens:
- name: type
  value: mysql
  export: TYPE
- name: host
  value: '[ "wodby.host" ]'
  export: HOST
- name: port
  value: '[ "wodby.containers.mariadb.port" ]'
  export: PORT
- name: username
  generate: '[ "wodby.stack.name" ]'
  export: USERNAME
- name: database
  generate: '[ "wodby.stack.name" ]'
  export: DATABASE
- name: password
  generate: '[ "wodby.password", {"length": 32} ]'
  export: PASSWORD
- name: root_password
  generate: '[ "wodby.password", {"length": 32} ]'
  
storage:
- name: data
  title: Data
  size: 10
  
integrations:
- name: backup-destination
  title: Backups destination (S3 compatible storage)
  type: s3-compat
  required: false
  jobsOnly: true  
  
# default
#  type: single-write
jobs:
- name: mysql-check
  title: mysql check
  command: ["mysql", "check"]
  type: post-deployment
- name: mysql-upgrade
  title: mysql upgrade
  command: ["mysql", "upgrade"]
  type: ugprade
