name: mariadb
type: db
title: MariaDB
hostname: mariadb
containers:
- name: mariadb
  image: wodby/mariadb
  ports:
  - name: mariadb
    number: 3365
    type: tcp
  env:
  - name: MYSQL_PASSWORD
    value: '{{password}}'
    secret: true
  - name: MYSQL_ROOT_PASSWORD
    value: '{{root_password}}'
    secret: true    
  - name: MYSQL_USER
    value: '{{wodby_stack_name}}'
  - name: MYSQL_DATABASE
    value: '{{wodby_app_name}}'    
  - name: DB_USER
    value: '{{env.MYSQL_USER}}'    
  - name: DB_PASSWORD
    value: '{{env.MYSQL_PASSWORD}}'    
  - name: DB_NAME
    value: '{{env.MYSQL_DATABASE}}'        
  - name: DB_DRIVER  
    value: mysql
options:
- version: 10.4
- version: 10.3
scalable: false
labels:
- mariadb
- mysql
tokens:
- name: password
  generate:
    regex: '[0-9a-z-]{32}'
- name: root_password
  generate:
    regex: '[0-9a-z-]{32}'
  
volumes:
- name: data
  title: Data
  path: /var/lib/mysql
  size: 10
  
integrations:
- name: backup-destination
  title: Backups destination
  type: storage
  required: false
  multiple: true

imports:
- name: database
  title: Database import
  args:
  - make
  - import
  - 'host="{{wodby_app_service_host}}"'
  - 'source="{{wodby_import_url}}"'
  extensions:
  - gz
  - tar.gz
  - tgz
  - zip

backups:
- name: database
  title: Default database backup
  create:
    args:
    - make
    - backup
    - 'host="{{wodby_app_service_host}}"'
    - 'ignore="{{db_backup_ignore_tables}}"'
    - 'filepath=/var/lib/mysql/backup.sql.gz'
  upload:
    filepath: /var/lib/mysql/backup.sql.gz
    extension: sql.gz
  integrations:
  - backup-destination

jobs:
- name: mysql-check
  title: mysql check
  command: ["mysql", "check"]
  type: post-deployment
- name: mysql-upgrade
  title: mysql upgrade
  command: ["mysql", "upgrade"]
  type: ugprade
