name: mariadb
type: db
title: MariaDB
hostname: mariadb
containers:
- name: mariadb
  image: wodby/mariadb
  ports:
  - name: mariadb
    number: 3365
  env:
  - name: MYSQL_PASSWORD
    value: '{{password}}'
    secret: true
  - name: MYSQL_ROOT_PASSWORD
    value: '{{root_password}}'
    secret: true    
  - name: MYSQL_USER
    value: '{{wodby_stack_name}}'
  - name: MYSQL_DATABASE
    value: '{{wodby_app_name}}'    
options:
- version: 10.4
- version: 10.3
scalable: false
labels:
- mariadb
- mysql
tokens:
- name: password
  generate:
    regex: '[0-9a-z-]{32}'
- name: root_password
  generate:
    regex: '[0-9a-z-]{32}'
  
volumes:
- name: data
  title: Data
  path: /var/lib/mysql
  size: 10
  
integrations:
- name: backup-destination
  title: Backups destination
  type: storage
  required: false
  jobsOnly: true  
  
import:
- name: data
  title: Database import
  archives:
  - tar
  - tar.gz
  - tgz
  - zip

# default
#  type: single-write
jobs:
- name: mysql-check
  title: mysql check
  command: ["mysql", "check"]
  type: post-deployment
- name: mysql-upgrade
  title: mysql upgrade
  command: ["mysql", "upgrade"]
  type: ugprade
